language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0-preview2
matrix:
  allow_failures:
    - rvm: 2.7.0-preview2

before_install:
  - gem update --system "2.7.10"
  - gem install bundler -v "1.17.3"
